# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('codcor', models.IntegerField(db_column='codCor', primary_key=True, serialize=False)),
                ('nomecor', models.CharField(db_column='nomeCor', max_length=20)),
                ('r', models.IntegerField(db_column='R')),
                ('g', models.IntegerField(db_column='G')),
                ('b', models.IntegerField(db_column='B')),
            ],
            options={
                'db_table': 'cor',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.IntegerField(db_column='idGrupo', primary_key=True, serialize=False)),
                ('nomegrupo', models.CharField(blank=True, db_column='nomeGrupo', max_length=20, null=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Iconespontos',
            fields=[
                ('codicone', models.AutoField(db_column='codIcone', primary_key=True, serialize=False)),
                ('imgicone', models.TextField(db_column='imgIcone')),
                ('nomeicone', models.CharField(db_column='nomeIcone', max_length=20)),
            ],
            options={
                'db_table': 'iconespontos',
            },
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('titulomapa', models.CharField(db_column='tituloMapa', max_length=30)),
                ('descmapa', models.TextField(db_column='descMapa')),
                ('idmapa', models.AutoField(db_column='idMapa', primary_key=True, serialize=False)),
                ('idtvisibilidade', models.CharField(db_column='idtVisibilidade', max_length=1)),
                ('valvisualizacoes', models.IntegerField(db_column='valVisualizacoes')),
                ('datamapa', models.DateField(db_column='dataMapa')),
                ('coordxinicial', models.FloatField(db_column='coordXInicial')),
                ('coordyinicial', models.FloatField(db_column='coordYInicial')),
                ('valaprovados', models.IntegerField(db_column='valAprovados')),
                ('valreprovados', models.IntegerField(db_column='valReprovados')),
            ],
            options={
                'db_table': 'mapa',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('idponto', models.AutoField(db_column='idPonto', primary_key=True, serialize=False)),
                ('coordx', models.FloatField(db_column='coordX')),
                ('coordy', models.FloatField(db_column='coordY')),
                ('nomponto', models.CharField(blank=True, db_column='nomPonto', max_length=30, null=True)),
                ('descponto', models.TextField(blank=True, db_column='descPonto', null=True)),
                ('fotoponto', models.TextField(blank=True, db_column='fotoPonto', null=True)),
                ('codcor', models.ForeignKey(blank=True, db_column='codCor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Cor')),
                ('codicone', models.ForeignKey(blank=True, db_column='codIcone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Iconespontos')),
            ],
            options={
                'db_table': 'ponto',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('datapostagem', models.DateField(db_column='dataPostagem')),
                ('horapostagem', models.TimeField(db_column='horaPostagem')),
                ('idpostagem', models.AutoField(db_column='idPostagem', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'postagem',
            },
        ),
        migrations.CreateModel(
            name='Postagemgrupo',
            fields=[
                ('datapostagem', models.DateField(db_column='dataPostagem')),
                ('horapostagem', models.TimeField(db_column='horaPostagem')),
                ('idpostagem', models.AutoField(db_column='idPostagem', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'postagemgrupo',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('idrota', models.AutoField(db_column='idRota', primary_key=True, serialize=False)),
                ('idtevitar', models.IntegerField(blank=True, db_column='idtEvitar', null=True)),
                ('nomerota', models.CharField(db_column='nomeRota', max_length=30)),
                ('descrota', models.TextField(db_column='descRota')),
            ],
            options={
                'db_table': 'rota',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codtema', models.IntegerField(db_column='codTema', primary_key=True, serialize=False)),
                ('nomtema', models.CharField(db_column='nomTema', max_length=20)),
            ],
            options={
                'db_table': 'tema',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('primnomeusuario', models.CharField(db_column='primNomeUsuario', max_length=25)),
                ('emailusuario', models.CharField(db_column='emailUsuario', max_length=50)),
                ('senhausuario', models.CharField(db_column='senhaUsuario', max_length=32)),
                ('datanascimento', models.DateField(db_column='dataNascimento')),
                ('idtsexo', models.CharField(db_column='idtSexo', max_length=1)),
                ('ultnomeusuario', models.CharField(db_column='ultNomeUsuario', max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('datamizade', models.DateField(db_column='datAmizade')),
                ('idusuario1', models.ForeignKey(db_column='idUsuario1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Usuario')),
            ],
            options={
                'db_table': 'amizade',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idmapa', models.ForeignKey(db_column='idMapa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Mapa')),
                ('idarea', models.CharField(db_column='idArea', max_length=20)),
                ('nomarea', models.CharField(db_column='nomArea', max_length=20)),
                ('descarea', models.TextField(db_column='descArea')),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('titulocomentario', models.CharField(db_column='tituloComentario', max_length=20)),
                ('txtcomentario', models.TextField(db_column='txtComentario')),
                ('datacomentario', models.DateField(db_column='dataComentario')),
                ('horacomentario', models.TimeField(db_column='horaComentario')),
                ('idusuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Usuario')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='Interesseusuariotema',
            fields=[
                ('codtema', models.ForeignKey(db_column='codTema', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Tema')),
                ('valvisualizacoes', models.IntegerField(db_column='valVisualizacoes')),
                ('idusuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario')),
            ],
            options={
                'db_table': 'interesseusuariotema',
            },
        ),
        migrations.CreateModel(
            name='Legenda',
            fields=[
                ('txtlegenda', models.TextField(db_column='txtLegenda')),
                ('idmapa', models.ForeignKey(db_column='idMapa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Mapa')),
                ('codicone', models.ForeignKey(db_column='codIcone', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Iconespontos')),
            ],
            options={
                'db_table': 'legenda',
            },
        ),
        migrations.CreateModel(
            name='Membrosgrupo',
            fields=[
                ('idgrupo', models.ForeignKey(db_column='idGrupo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Grupo')),
                ('idusuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario')),
            ],
            options={
                'db_table': 'membrosgrupo',
            },
        ),
        migrations.CreateModel(
            name='Permissaocolaboracao',
            fields=[
                ('idmapa', models.ForeignKey(db_column='idMapa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Mapa')),
                ('idusuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario')),
            ],
            options={
                'db_table': 'permissaocolaboracao',
            },
        ),
        migrations.CreateModel(
            name='RotaPonto',
            fields=[
                ('idrota', models.ForeignKey(db_column='idRota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Rota')),
                ('seqponto', models.IntegerField(blank=True, db_column='seqPonto', null=True)),
            ],
            options={
                'db_table': 'rota_ponto',
            },
        ),
        migrations.AddField(
            model_name='rota',
            name='codcor',
            field=models.ForeignKey(db_column='codCor', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Cor'),
        ),
        migrations.AddField(
            model_name='rota',
            name='idmapaevitado',
            field=models.ForeignKey(blank=True, db_column='idMapaEvitado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Mapa'),
        ),
        migrations.AddField(
            model_name='rota',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.AddField(
            model_name='postagemgrupo',
            name='idgrupo',
            field=models.ForeignKey(db_column='idGrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Grupo'),
        ),
        migrations.AddField(
            model_name='postagemgrupo',
            name='idmapa',
            field=models.ForeignKey(db_column='idMapa', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Mapa'),
        ),
        migrations.AddField(
            model_name='postagemgrupo',
            name='idusuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='idmapa',
            field=models.ForeignKey(blank=True, db_column='idMapa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Mapa'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='idusuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='idmapa',
            field=models.ForeignKey(db_column='idMapa', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Mapa'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='codtema',
            field=models.ForeignKey(db_column='codTema', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Tema'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='codcor',
            field=models.ForeignKey(blank=True, db_column='codCor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Cor'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.CreateModel(
            name='Pontoarea',
            fields=[
                ('idmapaarea', models.ForeignKey(db_column='idMapaArea', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Area')),
            ],
            options={
                'db_table': 'pontoarea',
            },
        ),
        migrations.AddField(
            model_name='rotaponto',
            name='idponto',
            field=models.ForeignKey(db_column='idPonto', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Ponto'),
        ),
        migrations.AlterUniqueTogether(
            name='postagemgrupo',
            unique_together=set([('idpostagem', 'idgrupo')]),
        ),
        migrations.AddField(
            model_name='comentario',
            name='idpostagem',
            field=models.ForeignKey(db_column='idPostagem', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Postagem'),
        ),
        migrations.AddField(
            model_name='area',
            name='codcor',
            field=models.ForeignKey(db_column='codCor', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Cor'),
        ),
        migrations.AddField(
            model_name='amizade',
            name='idusuario2',
            field=models.ForeignKey(db_column='idUsuario2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='id2', to='MapFindIt.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='rotaponto',
            unique_together=set([('idrota', 'idponto')]),
        ),
        migrations.AddField(
            model_name='pontoarea',
            name='idarea',
            field=models.ForeignKey(db_column='idArea', on_delete=django.db.models.deletion.DO_NOTHING, related_name='id2', to='MapFindIt.Area'),
        ),
        migrations.AddField(
            model_name='pontoarea',
            name='idponto',
            field=models.ForeignKey(db_column='idPonto', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Ponto'),
        ),
        migrations.AlterUniqueTogether(
            name='permissaocolaboracao',
            unique_together=set([('idmapa', 'idusuario')]),
        ),
        migrations.AlterUniqueTogether(
            name='membrosgrupo',
            unique_together=set([('idgrupo', 'idusuario')]),
        ),
        migrations.AlterUniqueTogether(
            name='legenda',
            unique_together=set([('idmapa', 'codicone')]),
        ),
        migrations.AlterUniqueTogether(
            name='interesseusuariotema',
            unique_together=set([('codtema', 'idusuario')]),
        ),
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together=set([('idusuario', 'idpostagem')]),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('idmapa', 'idarea')]),
        ),
        migrations.AlterUniqueTogether(
            name='amizade',
            unique_together=set([('idusuario1', 'idusuario2')]),
        ),
        migrations.AlterUniqueTogether(
            name='pontoarea',
            unique_together=set([('idmapaarea', 'idarea', 'idponto')]),
        ),
    ]
