# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='txtfrase',
            field=models.CharField(db_column='txtFrase', default='Frase filosófica', max_length=100),
            preserve_default=False,
        ),
    ]
