# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0002_usuario_txtfrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='topics/%Y/%m/%d/'),
        ),
    ]
