# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0005_auto_20170506_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='MapFindIt/static/MapFindIt/imagemUsers/'),
        ),
    ]
