# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0008_auto_20170507_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotaponto',
            name='idponto',
            field=models.ForeignKey(db_column='idPonto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MapFindIt.Ponto'),
        ),
        migrations.AlterField(
            model_name='rotaponto',
            name='idrota',
            field=models.ForeignKey(db_column='idRota', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Rota'),
        ),
    ]
