# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0009_auto_20170513_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='idusuario',
            field=models.ForeignKey(db_column='idUsuario', default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rota',
            name='idmapa',
            field=models.ForeignKey(blank=True, db_column='idMapa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Mapa'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='idmapaevitado',
            field=models.ForeignKey(blank=True, db_column='idMapaEvitado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evitado', to='MapFindIt.Mapa'),
        ),
    ]
