# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0010_auto_20170513_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='idtponto',
            field=models.CharField(blank=True, db_column='idtPonto', max_length=1),
        ),
    ]
