# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0011_ponto_idtponto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='codcor',
        ),
    ]
