# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0012_remove_ponto_codcor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaponto',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rotaponto',
            name='idponto',
            field=models.ForeignKey(db_column='idPonto', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Ponto'),
        ),
    ]
