# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0013_auto_20170520_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='codcor',
            field=models.ForeignKey(blank=True, db_column='codCor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Cor'),
        ),
    ]
