# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0014_ponto_codcor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='codcor',
        ),
    ]
