# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0016_auto_20170520_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoarea',
            name='idmapaarea',
        ),
    ]
