# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0017_remove_pontoarea_idmapaarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='idusuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together=set([]),
        ),
    ]
