# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0018_auto_20170521_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='amizade',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interesseusuariotema',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legenda',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrosgrupo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissaocolaboracao',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amizade',
            name='idusuario1',
            field=models.ForeignKey(db_column='idUsuario1', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
        migrations.AlterField(
            model_name='interesseusuariotema',
            name='codtema',
            field=models.ForeignKey(db_column='codTema', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Tema'),
        ),
        migrations.AlterField(
            model_name='legenda',
            name='idmapa',
            field=models.ForeignKey(db_column='idMapa', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Mapa'),
        ),
        migrations.AlterField(
            model_name='membrosgrupo',
            name='idgrupo',
            field=models.ForeignKey(db_column='idGrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Grupo'),
        ),
        migrations.AlterField(
            model_name='permissaocolaboracao',
            name='idmapa',
            field=models.ForeignKey(db_column='idMapa', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Mapa'),
        ),
    ]
