# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0027_auto_20170731_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperarSenha',
            fields=[
                ('idcodigo', models.AutoField(db_column='idArea', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='codigo', max_length=32)),
                ('idusuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario')),
            ],
            options={
                'db_table': 'CodigoRecuperarSenha',
            },
        ),
    ]
