# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0029_postagem_censurada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recomendacoes',
            field=models.BooleanField(db_column='recomendacoes', default=True),
        ),
    ]
