# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0030_usuario_recomendacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('idNotificacao', models.AutoField(db_column='idNotificacao', primary_key=True, serialize=False)),
                ('txtNotificacao', models.TextField(db_column='txtNotificacao')),
                ('linkNotificacao', models.TextField(db_column='linkNotificacao')),
            ],
        ),
    ]
