# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0031_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MapFindIt.Usuario'),
        ),
    ]
