# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0032_notificacao_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(db_column='lida', default=False),
        ),
    ]
