# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0033_notificacao_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='dataNotificacao',
            field=models.DateField(db_column='dataNotificacao', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacao',
            name='horaNotificacao',
            field=models.TimeField(db_column='horaNotificacao', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
