# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapFindIt', '0034_auto_20171031_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='nova',
            field=models.BooleanField(db_column='nova', default=True),
        ),
    ]
